### ISSUE TITLE
Comment cannot be cast to Page

### ISSUE THREAD

**Issue by pflan** [chris-kent/Confluence-Blog-Tools#38]
I'm getting an error when attempting to convert a permanent page with three comments into a blog post. Here's the top of the stack trace:

java.lang.ClassCastException: com.atlassian.confluence.pages.Comment cannot be cast to com.atlassian.confluence.pages.Page
	at net.kentcom.blogtools.PageToBlogListener.updateIncomingLinks(PageToBlogListener.java:275)
	at net.kentcom.blogtools.PageToBlogServlet.convertPageToBlog(PageToBlogServlet.java:168)
	at net.kentcom.blogtools.PageToBlogServlet.doPost(PageToBlogServlet.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.atlassian.plugin.servlet.DelegatingPluginServlet.service(DelegatingPluginServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.atlassian.plugin.servlet.ServletModuleContainerServlet.service(ServletModuleContainerServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

The full error is in the attached log excerpt: [2019-01-11-confluence-blogtools-error.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/2750385/2019-01-11-confluence-blogtools-error.txt)

I'm using these versions:

Confluence: 6.2.2
Blog Tools: 3.18

I'm currently in a trial version, but if we can get this working, I'm looking to buy the 2000 user license.

**Comment by chris-kent** [comment]
This has been fixed in version 3.19

**Comment by pflan** [comment]
It works now, thanks Chris!

**Comment by chris-kent** [comment]
No worries.
It was an interesting scenario i have not seen before.
Glad it is better
Cheers
